# Generated by Django 3.2.12 on 2022-10-30 18:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50, validators=[account.models.validate_password]),
        ),
    ]
