# Generated by Django 3.2.12 on 2022-10-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('username', 'password')},
        ),
    ]
