# Generated by Django 3.2.12 on 2022-10-30 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')])),
            ],
            options={
                'db_table': 'parents',
            },
        ),
    ]
