# Generated by Django 3.2.12 on 2022-10-27 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_alter_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')]),
        ),
    ]
