# Generated by Django 3.2.12 on 2022-10-24 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-z]*$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-z]*$')])),
                ('mark', models.IntegerField()),
                ('age', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='parent.parent')),
                ('subjects', models.ManyToManyField(related_name='students', to='subject.Subject')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
