# Generated by Django 3.2.12 on 2022-10-30 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')])),
                ('age', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='parent.parent')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
