# Generated by Django 3.2.12 on 2022-10-27 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')]),
        ),
    ]
