# Generated by Django 3.2.12 on 2022-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_subjects'),
        ('subject', '0002_alter_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='subjects', to='student.Student'),
        ),
    ]
