# Generated by Django 3.2.12 on 2022-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_subjects'),
        ('subject', '0003_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='student.Student'),
        ),
    ]
